// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Ty3zTkvoSBNtEdkp8cvbHRxI_VxZ8uQ',
    appId: '1:1067405232898:web:9e1cf9b4e6f6b0c9a6901b',
    messagingSenderId: '1067405232898',
    projectId: 'smart-energy-home-app',
    authDomain: 'smart-energy-home-app.firebaseapp.com',
    storageBucket: 'smart-energy-home-app.firebasestorage.app',
    measurementId: 'G-6G292BQKX1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZgtY76azpnz_waH53lvTw19GCO5vLGBk',
    appId: '1:1067405232898:android:a872ca8e81ba3eefa6901b',
    messagingSenderId: '1067405232898',
    projectId: 'smart-energy-home-app',
    storageBucket: 'smart-energy-home-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZyIBblL9zEh1xo1u6nKeJJm0DCFn-dO4',
    appId: '1:1067405232898:ios:77f34ab348ebbb47a6901b',
    messagingSenderId: '1067405232898',
    projectId: 'smart-energy-home-app',
    storageBucket: 'smart-energy-home-app.firebasestorage.app',
    iosClientId: '1067405232898-3vulvtvboohfj4s8649tvtogk4k81lal.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartEnergyHome',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZyIBblL9zEh1xo1u6nKeJJm0DCFn-dO4',
    appId: '1:1067405232898:ios:77f34ab348ebbb47a6901b',
    messagingSenderId: '1067405232898',
    projectId: 'smart-energy-home-app',
    storageBucket: 'smart-energy-home-app.firebasestorage.app',
    iosClientId: '1067405232898-3vulvtvboohfj4s8649tvtogk4k81lal.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartEnergyHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Ty3zTkvoSBNtEdkp8cvbHRxI_VxZ8uQ',
    appId: '1:1067405232898:web:b811c89c44ae139ca6901b',
    messagingSenderId: '1067405232898',
    projectId: 'smart-energy-home-app',
    authDomain: 'smart-energy-home-app.firebaseapp.com',
    storageBucket: 'smart-energy-home-app.firebasestorage.app',
    measurementId: 'G-2W38MT7317',
  );
}
