// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgxugMVJVcAenpdFRthmymU8kPcpXi-x4',
    appId: '1:585897514589:web:3bd0e0eecfa61e66e7dfb4',
    messagingSenderId: '585897514589',
    projectId: 'smart-energy-home-fd036',
    authDomain: 'smart-energy-home-fd036.firebaseapp.com',
    storageBucket: 'smart-energy-home-fd036.firebasestorage.app',
    measurementId: 'G-QMZ1BE9HWK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW86s24m66-jkpbr9iwpHxsKINb-3dicE',
    appId: '1:585897514589:android:9089c5eb0a0da545e7dfb4',
    messagingSenderId: '585897514589',
    projectId: 'smart-energy-home-fd036',
    storageBucket: 'smart-energy-home-fd036.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSlptrW7JDx1SW6EENk_73xSS57qjJKRs',
    appId: '1:585897514589:ios:02bb468bf8fc68f6e7dfb4',
    messagingSenderId: '585897514589',
    projectId: 'smart-energy-home-fd036',
    storageBucket: 'smart-energy-home-fd036.firebasestorage.app',
    iosClientId: '585897514589-40l21ao3rfl2eotrvuouchflnsnhfd08.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartEnergyHome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSlptrW7JDx1SW6EENk_73xSS57qjJKRs',
    appId: '1:585897514589:ios:02bb468bf8fc68f6e7dfb4',
    messagingSenderId: '585897514589',
    projectId: 'smart-energy-home-fd036',
    storageBucket: 'smart-energy-home-fd036.firebasestorage.app',
    iosClientId: '585897514589-40l21ao3rfl2eotrvuouchflnsnhfd08.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartEnergyHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgxugMVJVcAenpdFRthmymU8kPcpXi-x4',
    appId: '1:585897514589:web:eb2c8c20c5acbbdfe7dfb4',
    messagingSenderId: '585897514589',
    projectId: 'smart-energy-home-fd036',
    authDomain: 'smart-energy-home-fd036.firebaseapp.com',
    storageBucket: 'smart-energy-home-fd036.firebasestorage.app',
    measurementId: 'G-WLGC24M5JL',
  );
}
